---
output: pdf_document
---

# Conclusion

La salinité est une variable environnementale importante pour l’holobionte corallien. Cette étude a permis de montrer que la variation de salinité, même faible et sur une courte durée, impacte négativement l’espèce *S. hystrix*. Toutefois, cette espèce de corail hermatypique fait preuve d’une forte résilience dans ces conditions puisqu’au terme de l’expérience aucune mortalité n’a été observée et tous les individus ont récupéré (y compris leur coloration) en l’espace d’un mois.

Cependant, les études menées sur d’autres espèces de corail montrent une sensibilité ou résistance différente quant aux variations de salinité dépendant de facteurs tels que (1) l’amplitude de la variation saline, (2) la durée de cette variation, (3) la sensibilité de l’espèce ainsi que le clade de zooxanthelles présent dans les tissus coralliens.
Par conséquent, les résultats obtenus au cours de ce mémoire montrent une influence non négligeable d’un choc hypo- ou hypersalin mais ne sont pas applicables à toutes les espèces formant les récifs.
