---
bibliography: ../bibliography/coral_salinity_biblio.bib
output:
  word_document: default
  pdf_document:
    fig_caption: yes
    includes:
      in_header: template/preamble-latex-fr.tex
    latex_engine: xelatex
    number_sections: yes
---

# Introduction


## Les écosystèmes coralliens

### Généralités du milieu

Apparu il y a 65 millions d’années , les récifs coralliens sont des écosystèmes extrêmement riches et considérés comme les plus anciens de notre planète [@McIntyre2010, @Veron2000]. Ils recouvrent une superficie d’environ 250 000 km2 et sont très souvent comparés à la forêt tropicale avec laquelle ils partagent de nombreuses caractéristiques [@Richmond2011, @Rosenberg2007].

La richesse que renferme ces écosystèmes est énorme. En effet, ils possèdent la plus grande diversité par unité de surface ainsi que la plus grande diversité d’habitat formé par les milliers d’espèces de coraux qui les peuplent [@McIntyre2010]. Ces écosystèmes se sont formés grâce à l’association particulière des Scléractiniaires avec des algues photosynthétiques du genre Symbiodinium, les zooxanthelles, menant à une symbiose mutualiste permettant la prolifération de ces coraux symbiotiques dans ces environnements éventuellement très oligotrophes.

Cet écosystème marin, bien que fortement diversifié, ne se trouve que dans une zone délimitée du globe (\autoref{distri_coral}). Les récifs coralliens se développent dans des régions caractérisées par des conditions précises [@Burke2011] telles qu’une oligotrophie de l’eau, une forte irradiance, une température de l’eau variant entre 18°C et 34°C toute l’année et dont les variations sont faibles, et une turbidité de l’eau peu présente afin de permettre le passage de la lumière jusqu’au récif. Ces conditions très précises ne se trouvent qu’entre les tropiques, soit entre 30°N et 30°S. Il est à noter que certains récifs se forment dans des conditions toutes autres, tel que démontré récemment en Amazonie où un récif a été découvert à plus de 200m de profondeur et appelé « The Great Amazon Reef System [@Francini2018] ou au Japon où la température chute régulièrement entre 11-14°C [@Veron2000].

![Schéma représentant la distribution des récifs coralliens (en rouge) dans les océans du monde. Les zones en bleu représentent les récifs possédant des coraux en symbioses avec des zooxaanthelles [@Veron2000]. \label{distri_coral}](images/distri_coral.png)

Les récifs intertropicaux sont construits par des scléractinaires dits hermatypiques. Trois grands types de récifs existent sur Terre  et dérivent les uns des autres \autoref{recif_type} : les récifs frangeants, les récifs barrière et les atolls [@Veron2000, @Cesar2003]. Les récifs frangeants sont des récifs se formant sur les bords du littoral et se trouvent par conséquent proches des côtes où ils forment un platier de faible profondeur appelé « le lagon ». Ce type de récifs est retrouvé, par exemple, autour de l’île de la Réunion. Le récif barrière quant à lui forme une structure plus éloignée des côtes comme observée au niveau de la Grande Barrière de Corail en Australie et provient d’un enfoncement progressif des terres. Pour finir, les atolls sont des structures retrouvées en pleine mer et sont de forme circulaire renfermant le lagon. Ce type de récifs se forme par enfoncement et disparition de l’île autour de laquelle il s’est formé. Les atolls peuvent être observés, par exemple, aux Maldives.

![Schéma représentant la formation des différents types de récifs. L'image représente un récif frangeant (à gauche), un récif barrière ( au centre) et un atoll (à droite) et montre le lien entre la formation de ces récifs [@Veron2000]\label{recif_type}](images/recif_type.png)


